services:
  wan:
    image: gogoshine/wan:latest
    ports:
      - "8000:8000"
    environment:
      # 用于将容器内部的文件路径转成URL，本质是将/app/替换成DOWNLOAD_URL得到下载路径
      - DOWNLOAD_URL=${DOWNLOAD_URL:-http://127.0.0.1/}
      - MODEL_SOURCE=${MODEL_SOURCE:-huggingface}
      - HF_TOKEN=${HF_TOKEN:-}
      - HF_ENDPOINT=${HF_ENDPOINT:-}
      - MODELSCOPE_TOKEN=${MODELSCOPE_TOKEN:-}
    volumes:
      - ./Wan2.2-TI2V-5B:/app/Wan2.2-TI2V-5B
      - ./output:/app/output
    gpus: all
    shm_size: 16gb
    restart: unless-stopped
