name: wan

services:
  wan:
    image: gogoshine/wan:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: wan
    ports:
      - "8000:8000"
    environment:
      # 用于将容器内部的文件路径转成URL，本质是将/app/替换成DOWNLOAD_URL得到下载路径
      - DOWNLOAD_URL=${DOWNLOAD_URL:-http://127.0.0.1/}
      - HF_TOKEN=${HF_TOKEN:-}
      - HF_ENDPOINT=${HF_ENDPOINT:-https://huggingface.co}
      - COMFY_POLL_TIMEOUT=${COMFY_POLL_TIMEOUT:-7200}
    volumes:
      # ComfyUI 模型目录（断点续传）
      - ./models:/app/ComfyUI/models
      # API 输出视频
      - ./output:/app/output
    gpus: all
    shm_size: 16gb
    restart: unless-stopped
